### ISSUE TITLE
homepage formatting

### ISSUE THREAD

**Issue by g00dL00Ks** [g00dL00Ks/ruby#1]
I'm having trouble getting our custom font to pull throughout the site.  Also, the homepage, some of the formatting is not coming out the same as our mock-up (see attached)

[HTML.zip](https://github.com/g00dL00Ks/ruby/files/93095/HTML.zip)

**Comment by nolanzandi** [comment]
I'll start with this one.

**Comment by nolanzandi** [comment]
Hey sorry, could you take a quick screenshot of a piece of content that is supposed to have a custom font and doesnt and tell me what font that piece of content should have. I'm having trouble locating the trouble spots.

**Comment by g00dL00Ks** [comment]
this is how the text on the header looks in our mock-up.  You can see it's much bigger. (this is also in the html zip i sent you)

![image](https://cloud.githubusercontent.com/assets/14116569/12374775/5243935a-bc5b-11e5-8cc6-f9f305f7a69c.png)

**Comment by nolanzandi** [comment]
![image](https://cloud.githubusercontent.com/assets/2481116/12374991/ee58373a-bc62-11e5-92b5-6c050a72c629.png)

Ok so I've got the basics of what you asked (text etc). Do you want me to just keep working on making the page look like the mockup?

Total time so far on task: 1 hours

**Comment by g00dL00Ks** [comment]
Yes please. But don't spend too much time. I think close enough is ok

On Sat, Jan 16, 2016 at 3:07 PM -0800, "Nolan Zandi" <notifications@github.com<mailto:notifications@github.com>> wrote:

[image]https://cloud.githubusercontent.com/assets/2481116/12374842/75ed2d2c-bc5e-11e5-9578-1058b62efee8.png
[image]https://cloud.githubusercontent.com/assets/2481116/12374984/b36e8782-bc62-11e5-92cf-6378f92f8092.png

Ok so I've got the basics of what you asked (text etc). Do you want me to just keep working on making the page look like the mockup?

##

**Comment by g00dL00Ks** [comment]
The changes you made worked locally for me, but when I just pushed it to heroku, it lost all the fonts again.  you can see it at:
http://insider.marsmerize.com/

Also, any idea why the photos on the pages aren't centered?  Even though there is a centered class on them?

thank you!

**Comment by nolanzandi** [comment]
I can see the issue. It looks like in production it thinks the fonts are in assets but they are actually in assets/fonts (see below)
![image](https://cloud.githubusercontent.com/assets/2481116/12376719/03c92c96-bcb8-11e5-8ff4-ced59484db6a.png)

I think, due to Rails and Ruby versions that your using, that I shouldn't have changed the "font-url" part of the font-face configuration to just "url". I changed it back and pushed my commit to my branch: https://github.com/g00dL00Ks/ruby/commit/ded73721d9b1831ddaee414340e615d9f939f211

I also deployed to the server for testing and it looks like it worked: http://insider.marsmerize.com/

![image](https://cloud.githubusercontent.com/assets/2481116/12376893/52398668-bcbe-11e5-8fe2-6b92cf14276c.png)

Sorry about that, different ruby and rails versions can be so different (I'm guessing the ruby/rails version in production is different than on our home computers) that these kinds of these happen.

As far as why photos aren't centered, it looks like the center class is trying to center photos with the css property "align: center" which doesn't do anything (unlike with text which can be aligned with "text-align:center".

![image](https://cloud.githubusercontent.com/assets/2481116/12376885/1ead77c8-bcbe-11e5-8358-6bfc9fcac7d3.png)

 To center a photo or div you need to use the property "margin:auto". I know that isn't intuitive but its the way to do it. I can align all the photos for you tomorrow, so let me know if you'd like me to do that. See my example below:

![image](https://cloud.githubusercontent.com/assets/2481116/12376890/2f8c12d4-bcbe-11e5-84e9-cbb02fb9386a.png)

Total time so far: 2 hours

**Comment by g00dL00Ks** [comment]
Thank you! I made this change on the CSS and it looks great.  appreciate it.  

Does your schedule permit you to help today with the pro photos?

**Comment by g00dL00Ks** [comment]
Ok I made some more changes to the homepage and a few other static pages.  But now i can't commit to heroku b/c your version is committed.  I find the git branches quite counter-intuitive.  I merged your branch with master and pulled it down to my local console and re-committed to git.  But when I push to heroku I get this error:
To https://git.heroku.com/goodlooks.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://git.heroku.com/goodlooks.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

can you push the latest changes I've made?  or let me know how to do it.  

thank you!

**Comment by nolanzandi** [comment]
I pushed the latest changes. And below is how to fix that issue (first answer):

http://stackoverflow.com/questions/18669963/cannot-push-to-heroku-after-adding-a-remote-heroku-repo-to-my-existing-local-rep

I do have some other deadlines today so it'll be a little tight, but I should have a couple hours to work on the pros photos.

**Comment by g00dL00Ks** [comment]
Thanks - i've done this but keeping getting the error.  I'll just do git push heroku master -f

**Comment by nolanzandi** [comment]
Yep git push heroku master -f should work (and I just tested it on my computer, worked fine)

**Comment by g00dL00Ks** [comment]
Ok i think we are in good shape on this, so i'm going to close it out!
