### ISSUE TITLE
Unable to delete a service

### ISSUE THREAD

**Issue by g00dL00Ks** [g00dL00Ks/ruby#8]
@nolanzandi 
I'm trying to add in 'delete' for service on this page:
http://localhost:3000/pros/ID

but i get in response 
SystemStackError in ServicesController#destroy
stack level too deep

The code is commented out at:
app>views>pros>show
as:
<%=  link_to 'Delete', pro_service_path(service, current_user.pro.id), method: :delete, data: { confirm: 'Are you sure?' }  %> </p>

Can you help me add in a delete option?  In can also be on the edit service page.

It would also be good to have a delete option for the photos as well.  

I couldn't get it to work myself

**Comment by nolanzandi** [comment]
So Services and photos can now be deleted. There were several issues to work through but the main issue was that, in your services and photos controller you had:

belongs_to :pro, foreign_key: "pro_id", dependent: :destroy

What that means is that you want to destroy the dependent database associatiions (IE, destroy the Pro when  you destroy the services). You generally want dependent: :destroy in top level models, such as the Pro model so that services and photos are deleted in the case of a pro being deleted, but not the other way around. 

![image](https://cloud.githubusercontent.com/assets/2481116/12439406/26786cbe-bee5-11e5-8ea9-b1043b552bd2.png)

![image](https://cloud.githubusercontent.com/assets/2481116/12439410/2f6af0da-bee5-11e5-8409-ad9b01aa3638.png)

I've pushed changes live to the server to checkout. 

Total time on project so far: 1.5 hours

**Comment by g00dL00Ks** [comment]
Thank you!  I didn't know that about the associations so thank you for the info

On Tue, Jan 19, 2016 at 8:22 PM -0800, "Nolan Zandi" <notifications@github.com<mailto:notifications@github.com>> wrote:

So Services and photos can now be deleted. There were several issues to work through but the main issue was that, in your services and photos controller you had:

belongs_to :pro, foreign_key: "pro_id", dependent: :destroy

What that means is that you want to destroy the dependent database associatiions (IE, destroy the Pro when you destroy the services). You generally want dependent: :destroy in top level models, such as the Pro model so that services and photos are deleted in the case of a pro being deleted, but not the other way around.

[image]https://cloud.githubusercontent.com/assets/2481116/12439406/26786cbe-bee5-11e5-8ea9-b1043b552bd2.png

[image]https://cloud.githubusercontent.com/assets/2481116/12439410/2f6af0da-bee5-11e5-8409-ad9b01aa3638.png

I've pushed all changes to my branch on Github: 79af3bdhttps://github.com/g00dL00Ks/ruby/commit/79af3bdc0399c9d07ffe9ee05629c6d685d9b43e

Total time on project so far: 1.5 hours

##

**Comment by g00dL00Ks** [comment]
Working well - thank you!
